# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x1a\x1bgoogle/protobuf/empty.proto\"a\n\x04\x44\x61ta\x12\x10\n\x08\x44\x65\x63imal1\x18\x01 \x02(\x02\x12\x10\n\x08\x44\x65\x63imal2\x18\x02 \x02(\x02\x12\x10\n\x08\x44\x65\x63imal3\x18\x03 \x02(\x02\x12\x10\n\x08\x44\x65\x63imal4\x18\x04 \x02(\x02\x12\x11\n\tTimestamp\x18\x05 \x02(\x03\"d\n\x06Packet\x12\x17\n\x0fPacketTimestamp\x18\x01 \x02(\x03\x12\x14\n\x0cPacketSeqNum\x18\x02 \x02(\x05\x12\x10\n\x08NRecords\x18\x03 \x02(\x05\x12\x19\n\nPacketData\x18\x04 \x03(\x0b\x32\x05.Data\"\x12\n\x03\x41\x63k\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08\x32<\n\x0b\x44\x61taService\x12-\n\nSendPacket\x12\x07.Packet\x1a\x16.google.protobuf.Empty')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATA']._serialized_start=43
  _globals['_DATA']._serialized_end=140
  _globals['_PACKET']._serialized_start=142
  _globals['_PACKET']._serialized_end=242
  _globals['_ACK']._serialized_start=244
  _globals['_ACK']._serialized_end=262
  _globals['_DATASERVICE']._serialized_start=264
  _globals['_DATASERVICE']._serialized_end=324
# @@protoc_insertion_point(module_scope)
